### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Tetsuuko** [pasqualerossi/42-School-Exam-Rank-04#10]
A lot of big mistakes in this code, it s odd that the moulinette allowed this to pass :  

- STDIN and STDOUT are not restored at the end of a pipeline, args like ./microshell "/bin/echo" "a" "|" "/bin/cat" "-e" "|" "/bin/wc" "-l" ";" "/bin/cat" will not work correctly (the last cat should read on STDIN).

- Commands in a pipeline do not work simultaneously, args like ./microshell "/bin/yes" "|" "head" "-n" "20"  will result in an infinite loop because the 'head' command will never start and cant sigpipe the first command. You must launch each command of the pipeline before waiting with waitpid.

It's disappointing to promote this kind of program even though the moulinette won't KO it.

**Comment by madfcat** [comment]
https://github.com/pasqualerossi/42-School-Exam-Rank-04/pull/9

You can check this pull request with a fix. It was not merged though 🥺
