### ISSUE TITLE
Using the `__environ` variable. 

### ISSUE THREAD

**Issue by multitudes** [pasqualerossi/42-School-Exam-Rank-04#17]
it is reported that using the `__environ` is not allowed in the test.
In general, it's recommended to use `environ` rather than `__environ`, because environ is standardized by POSIX and is more portable across different systems. The __environ variable is not standardized and might not be available on all systems.
I would advise to use:
```
extern char **environ;
```
which is not a global and it is posix compliant.

**Comment by pasqualerossi** [comment]
create a pull request and I'll update it. Thanks!

**Comment by multitudes** [comment]
Ok thanks!
